import path from 'node:path';
import { readFile } from 'node:fs/promises';

import { describe, expect, it } from 'vitest';

import { runTypesCommand } from '../src/commands/types';
import { createTempDir, createTestContext, repoRootFromTest } from './helpers';

describe('types command', () => {
  it('generates deterministic type output from example policy', async () => {
    const repoRoot = repoRootFromTest(import.meta.url);
    const tempDir = await createTempDir();
    const outFile = path.join(tempDir, 'policy-types.ts');

    const { context } = createTestContext(repoRoot);

    const code = await runTypesCommand({
      policyPath: 'examples/policies/basic.policy.json',
      outPath: outFile,
      context,
    });

    expect(code).toBe(0);

    const content = await readFile(outFile, 'utf8');

    expect(content).toBe(
      [
        '/* eslint-disable */',
        '// Generated by acx types. Do not edit manually.',
        '',
        "export const POLICY_VERSION = '1.0.0' as const;",
        '',
        "export const ACTION_PATTERNS = ['payment:approve', 'post:delete', 'post:read', 'post:update'] as const;",
        'export type ActionPattern = typeof ACTION_PATTERNS[number];',
        '',
        "export const ACTION_NAMES = ['payment:approve', 'post:delete', 'post:read', 'post:update'] as const;",
        'export type ActionName = typeof ACTION_NAMES[number];',
        '',
        "export const RESOURCE_TYPES = ['payment', 'post'] as const;",
        'export type ResourceType = typeof RESOURCE_TYPES[number];',
        '',
      ].join('\n'),
    );
  });
});
